####################
# 配置文件 #
####################

name 		=	"Masterlab Socket Server"
enable 		= 	true
status 		= 	"dev"
version		=	"1.0"
loglevel	=	"info"
single_mode	=	true

[connector]
    socket_port    	= 9002
    websocket_port 	= 9898
    max_conections 	= 5024
    max_packet_rate	= 100
    max_conntions_ip= 100
    max_packet_rate_unit = 10
    auth_cmds = ["Auth","Authorize"]

[masterlab_db]
    database 	=	"masterlab_dev"
    host        =   "47.244.62.11"
    user 		= 	"remote_mysql_user"
    password 	= 	"Hornet123"
    port		=	"3306"
    charset	    =	"utf8mb4_unicode_ci"
    timeout	    =	"30"

[object]
    data_type 	= "redis"
    redis_host 	= "127.0.0.1"
    redis_port 	= "6379"
    redis_password = ""

[worker]
    #  在分布式模式下 连接到worker servers的ip和端口
    to_servers = []

[hub]
    hub_host = "127.0.0.1"
    hub_port = "7302"

[area]
    init_area = ["area-global", "area-global2", "area-global3"]

[admin]
    http_port = "9090"

[log]
    log_level	=	"error"
    mongodb_host = "localhost"
    mongodb_port = "27017"