####################
# worker 配置文件   #
####################

loglevel	=	"error"
rpc_type	=	"go"
single_mode	=	false

# worker 本身的服务地址和端口

# 连接到hub server
connect_to_hub = ["127.0.0.1" ,"7302"]

# 数据库配置
    database 	=	"masterlab_dev"
    host        =   "47.244.62.11"
    user 		= 	"remote_mysql_user"
    password 	= 	"Hornet123"
    port		=	"3306"
    charset	    =	"utf8mb4_unicode_ci"
    timeout	    =	"30"
    max_open_conns   =   2000
    max_idle_conns   =   1000
		
      