    # demo webim 数据库连接配置

    database 	=	"masterlab_dev"
    host        =   "47.244.62.11"
    user 		= 	"remote_mysql_user"
    password 	= 	"Hornet123"
    port		=	"3306"
    charset	    =	"utf8mb4_unicode_ci"
    timeout	    =	"30"
